# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashtable.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhashtable.proto\x1a\x1egoogle/protobuf/wrappers.proto\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"%\n\x05Value\x12\x12\n\x05value\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_value2\x86\x01\n\tHashTable\x12\x31\n\x06Insert\x12\t.KeyValue\x1a\x1a.google.protobuf.BoolValue\"\x00\x12,\n\x06\x44\x65lete\x12\x04.Key\x1a\x1a.google.protobuf.BoolValue\"\x00\x12\x18\n\x06LookUp\x12\x04.Key\x1a\x06.Value\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hashtable_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=51
  _KEYVALUE._serialized_end=89
  _KEY._serialized_start=91
  _KEY._serialized_end=109
  _VALUE._serialized_start=111
  _VALUE._serialized_end=148
  _HASHTABLE._serialized_start=151
  _HASHTABLE._serialized_end=285
# @@protoc_insertion_point(module_scope)
